### PR TITLE
fix(Exception when no clients exist in the DB)

### LINKED ISSUE #47: Exception when no clients exist in the DB
### Summary

```markdown
The application crash when the application tries to load all the clients.
The exception occur because the JSON, retrieved from the API, doesn't contain an excepted object that contain the clients (when their exist).
```

### How to reproduce

```markdown
1. Empty your client TABLE
2. Go to the list client page
3. **See error**
```

### Expected behavior

```markdown
No error but a message that display "No clients" or something like that
```

### Screenshot

_No response_

### Stacktrace

_No response_

### Other detail

_No response_

### PR DESCRIPTION
**Pull request by Mateofsr**

### CODE REVIEW

File: app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/ClientService.java [hunk 1]
```diff
@@ -59,13 +59,15 @@ public static void getClients(Context context, ListView listClientsView) {
...
-
-                        List<Client> clientsArray = new ArrayList<>(clients.length());
-                        for (int i = 0; i < clients.length(); i++) {
-                            clientsArray.add((new Client(clients.getJSONObject(i))));
+                        List<Client> clientsArray = new ArrayList<>();
+                        if (response.has("_embedded")) {
+                            JSONArray clients = response.getJSONObject("_embedded").getJSONArray("clientList");
+                            Log.d(TAG, "getClients: " + clients);
+                            for (int i = 0; i < clients.length(); i++) {
+                                clientsArray.add((new Client(clients.getJSONObject(i))));
```
Comment (Odonata971) [inline app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/ClientService.java:67]: Inutil parenthesis

**Review by Odonata971 — CHANGES_REQUESTED** [review]

**Review by Odonata971 — APPROVED** [review]
LGTM
